apiVersion: v1
name: raw
home: https://github.com/md-stack-org/helm-charts/blob/main/charts/raw
version: 0.2.5
appVersion: 0.2.3
description: A place for all the Kubernetes resources which don't already have a home.
